export const REGISTERED_SUCCESSFULLY = "REGISTERED_SUCCESSFULLY";
export const REGISTERED_ERROR = "REGISTERED_ERROR";
export const GET_USER = "GET_USER";
export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CLOSE_SESSION = "CLOSE_SESSION";
